### ISSUE TITLE
"options" not working every time

### ISSUE THREAD

**Issue by macx** [OblikStudio/kirby-link-field#18]
In my following blueprint, the "option" is not working as expected. It should only display a page, but it's using the default (url).

![image](https://user-images.githubusercontent.com/84112/76206097-b5065c80-61fb-11ea-82de-96ca69dd9b8d.png)

**Comment by hdodov** [comment]
I tried with the exact same field blueprint and it works as expected. Have you set any global settings for `oblik.linkField.options` in your `config.php`? Post more info.

**Comment by macx** [comment]
No default settings at all. I tried a new page template, same result:

```yaml
fields:
  demo:
    label:
      en: Booking button
      de: Buchung-Button
    type: link
    options:
      - tel
    settings:
      text:
        width: 2/3
      popup:
        width: 1/3
      hash: false
```

**Comment by foxacid** [comment]
I'm experiencing the same issue with link field `2.0.1` and Kirby `3.3.5`. It works when adding a second option but breaks with a single option. 

```yaml
test:
  type: link
  label: Link
  options:
    - page
  pages:
    image:
      back: white
  settings:
    popup: false
    hash: false
```
