### ISSUE TITLE
Call to a member function url() on null - with toLinkObject() in Kirby 3.5.6

### ISSUE THREAD

**Issue by Maybach91** [OblikStudio/kirby-link-field#48]
I’m trying to get the URL of the link field like so:

```php
$link = $teammember->link()->toLinkObject();
var_dump($link->url());
```
  
I get the following error:
`Call to a member function url() on null`
  

**Blueprint:**
```yaml
link:
  label: Link (optional)
  help: z.B. zum Verlinken des Namens auf einen Lebenslauf
  type: link
```
  

`$link` has to following var_dump:
```php
  ["data":protected]=>
  array(2) {
    ["type"]=>
    string(4) "page"
    ["value"]=>
    string(17) "vita-malte-flatau"
  }
```
  
And `$teammember->link()` the following var_dump:
```php
  ["link"]=>
  array(2) {
    ["type"]=>
    string(4) "page"
    ["value"]=>
    string(17) "vita-malte-flatau"
  }
```

Whats wrong here? I just want the value. with `$teammember->link()->value()` i get the array as well. 
```json
"link": {
    "type": "page",
    "value": "vita-malte-flatau"
}
```
