### ISSUE TITLE
The field type "hash" does not exist

### ISSUE THREAD

**Issue by janstieler** [OblikStudio/kirby-link-field#57]
Hi,
I try to generate a block only with your field.
But I got the error
> The field type "hash" does not exist

Here is my blueprint
```yml
name: Link Block
icon: url
fields:
  link:
    type: link
    label: Link
    linkTypes:
      - page
      - url
    settings:
      popup:
        width: 1/3
        label: External Link
        help: Open link in a new tab?
      text:
        width: 2/3
      hash: true
 ```
