### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [OblikStudio/kirby-link-field#82]
UI broken for K4

![screen-capture-1762-link - Mægazine-plugins test](https://github.com/OblikStudio/kirby-link-field/assets/3393422/0e11e273-4829-4c8b-8be9-6c340ca891c4)

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by hdodov** [comment]
I think the correct course here is to just deprecate the plugin. As of Kirby 4.0, it has [its own link field](https://getkirby.com/docs/reference/panel/fields/link), so it doesn't make sense to use a plugin.

**Comment by foxacid** [comment]
I've used this plugin in quite a few projects over the years (many thanks!). While Kirby 4 has a much more flexible Link field than ye olde Url field it does not replace this plugin. Most notably, Kirby's built-in Link field is missing the extra `text` and  `popup` options. It would of course be possible to supply those via additional fields but upgrading more complex v3 projects to v4 would be a major pain... Or am i missing something?

**Comment by afbora** [comment]
@owzim I installed manually (download zip file), not via composer.

**Comment by owzim** [comment]
@foxacid same here. the core link field is a major let down compared to this one.

1. no search
2. looks totally different than other reference fields like files and pages
3. behave differently
4. misses things like label and popup
5. the value stored in the page file is only the value, no type like `email` or `page`, you would have to parse and in some cases guess, what type of value is stored

Unfortunately I cannot mention @OblikStudio but we would like to fork this project and continue support and development.

**Comment by foxacid** [comment]
@owzim that sounds great. the plugin developer is @hdodov so your best bet is to reach out to him.

**Comment by afbora** [comment]
@hdodov I suggest you keep up-to-date the plugin for v3 and next kirby releases. I can say that extra features such as target, link text will not come to the core link field in the near future.

We recommend extending the core link field using object field:
https://getkirby.com/docs/reference/panel/fields/link#adding-target-link-text-etc

**Comment by owzim** [comment]
@afbora @foxacid 

I reviewed object field ***again***, having it dismissed before because the preview for the link field sucks, but the `pages`, `files` and `url` field, selectively hidden based on selected types, it's very usable and quite pretty:

```yml
link:
  type: object
  fields:
    type:
      type: select
      label: Type
      options:
        page: Page
        image: Image
        url: URL
    page:
      type: pages
      max: 1
      when:
        type: page
    image:
      type: files
      max: 1
      when:
        type: image
    url:
      type: url
      when:
        type: url
    text:
      type: text
      label: Text
    newtab:
      type: toggle
      label: Open in new tab
```

![image](https://github.com/OblikStudio/kirby-link-field/assets/1720088/51e9fd7c-2067-4b8d-8745-912e5e3799a8)
![image](https://github.com/OblikStudio/kirby-link-field/assets/1720088/9c137409-acdb-45b5-a7be-005cff3cf4ad)
![image](https://github.com/OblikStudio/kirby-link-field/assets/1720088/d5da3d23-17cc-4ae6-bb35-67a93d8c878a)

drawer:

![image](https://github.com/OblikStudio/kirby-link-field/assets/1720088/0b5f7311-6eda-4f8b-ab93-092ec2cfba4f)
